server:
  port: 8870
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 3600m


spring:
  datasource:
    url : jdbc:mysql://localhost:3306/jeesns?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    order: 0
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    classic-compatible: true
    whitespace-stripping: true
    tag-syntax: auto_detect
    template-update-delay: 0
    default-encoding: UTF-8
    output-encoding: UTF-8
    locale: zh_CN
    date-format: yyyy-MM-dd
    time-format: HH:mm:ss
    datetime-format: yyyy-MM-dd HH\:mm\:ss
    number-format: \#.##
  logging:
    level: com.ibatis:DEBUG
  http:
    encoding:
      charset: utf-8
      enabled: true
  messages:
    encoding: UTF-8
    basename: i18n/messages

mybatis:
  typeAliasesPackage: com.lxinet.jeesns.model
  mapperLocations: classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-server.xml

jeesns:
  managePath: manage
  groupPath: group
  weiboPath: weibo
  frontTemplate: front
  memberTemplate: member
  manageTemplate: manage
  mobileTemplate: mobile